version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: ampora_postgres
    restart: always
    environment:
      POSTGRES_DB: ampora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: numidu/ampora_backend:latest
    container_name: ampora_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ampora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SERVER_PORT: 8083

      PAYHERE_MERCHANT_ID: "1228213"
      PAYHERE_MERCHANT_SECRET: "NzY1ODg5MzAzMTk5NTA0NDI3Mjk0NDcxNzE4NDQ0NDA3NjgzOQ=="
      PAYHERE_CURRENCY: "LKR"
      PAYHERE_SANDBOX: "true"
      GOOGLE_CLIENT_ID: "1036320353420-nnvlhjidmtj36mucnfu78bu4r5ndotcp.apps.googleusercontent.com"
      JWT_SECRET: "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"

volumes:
  postgres_data:
